const NONE_COLOR = "#111111";

const colorScales = {
  econDisadv: [
    "step",
    ["get", "econDisadv"],
    NONE_COLOR, // default color for low values
    0.1,
    "#FEB24C",
    1000,
    "#FD8D3C",
    2000,
    "#FC4E2A",
    3000,
    "#E31A1C",
  ],
  totalStudents: [
    "step",
    ["get", "totalStudents"],
    NONE_COLOR, // Default color if no data (use a neutral color)
    0.1,
    "#FFFFB2", // Light yellow for the smallest values
    1000,
    "#ADDD8E", // Light green for moderate values
    2000,
    "#78C679", // Medium green for higher values
    3000,
    "#31A354", // Dark green for even higher values
  ],
  percentDisadv: [
    "step",
    ["get", "percentDisadv"],
    NONE_COLOR,
    0.01,
    "#FEB24C",
    0.4,
    "#FD8D3C",
    0.6,
    "#FC4E2A",
    0.8,
    "#E31A1C",
    1,
    "#BD0026",
  ],
  povertyPercent: [
    "step",
    ["get", "povertyPercent"],
    NONE_COLOR,
    0.001,
    "#FEB24C",
    0.2,
    "#FD8D3C",
    0.3,
    "#FC4E2A",
    0.4,
    "#E31A1C",
    0.5,
    "#BD0026",
  ],
  percentCommunityDifference: [
    "step",
    ["get", "percentCommunityDifference"],
    NONE_COLOR,
    0.001,
    "#FEB24C",
    1,
    "#FD8D3C",
    2,
    "#FC4E2A",
    3,
    "#E31A1C",
    5,
    "#BD0026",
  ],
  population: [
    "step",
    ["get", "population"],
    "#FFFFB2",
    10000,
    "#ADDD8E",
    20000,
    "#78C679",
    30000,
    "#31A354",
    40000,
    "#006837",
    50000,
    "#006837",
  ],
  numberOfSchools: [
    "step",
    ["get", "numberOfSchools"],
    NONE_COLOR,
    1,
    "#FFFFB2",
    2,
    "#ADDD8E",
    3,
    "#78C679",
    4,
    "#31A354",
    5,
    "#006837",
  ],
};

const legendData = {
  econDisadv: [
    { color: NONE_COLOR, label: "No Students" },
    { color: colorScales.econDisadv[4], label: "1 - 1000" },
    { color: colorScales.econDisadv[6], label: "1000 - 2000" },
    { color: colorScales.econDisadv[8], label: "2000 - 3000" },
    { color: colorScales.econDisadv[10], label: "3000 - 4000" },
  ],
  totalStudents: [
    { color: NONE_COLOR, label: "No Students" },
    { color: colorScales.totalStudents[4], label: "1 - 1000" },
    { color: colorScales.totalStudents[6], label: "1000 - 2000" },
    { color: colorScales.totalStudents[8], label: "2000 - 3000" },
    { color: colorScales.totalStudents[10], label: "3000 - 4000" },
  ],
  percentDisadv: [
    { color: NONE_COLOR, label: "No Students" },
    { color: colorScales.percentDisadv[4], label: "< 20%" },
    { color: colorScales.percentDisadv[6], label: "20% - 40%" },
    { color: colorScales.percentDisadv[8], label: "40% - 60%" },
    { color: colorScales.percentDisadv[10], label: "60% - 80%" },
    { color: colorScales.percentDisadv[12], label: "> 80%" },
  ],
  povertyPercent: [
    { color: NONE_COLOR, label: "No Students" },
    { color: colorScales.povertyPercent[4], label: "< 20%" },
    { color: colorScales.povertyPercent[6], label: "20% - 30%" },
    { color: colorScales.povertyPercent[8], label: "30% - 40%" },
    { color: colorScales.povertyPercent[10], label: "> 40%" },
  ],
  percentCommunityDifference: [
    { color: NONE_COLOR, label: "No Students" },
    { color: colorScales.percentCommunityDifference[4], label: "< 100%" },
    { color: colorScales.percentCommunityDifference[6], label: "100% - 200%" },
    { color: colorScales.percentCommunityDifference[8], label: "200% - 300%" },
    { color: colorScales.percentCommunityDifference[10], label: "> 300%" },
  ],
  population: [
    { color: NONE_COLOR, label: "No Data" },
    { color: colorScales.population[4], label: "< 20,000" },
    { color: colorScales.population[6], label: "20,000 - 30,000" },
    { color: colorScales.population[8], label: "30,000 - 40,000" },
    { color: colorScales.population[10], label: "> 40,000" },
  ],
  numberOfSchools: [
    { color: NONE_COLOR, label: "No Schools" },
    { color: colorScales.numberOfSchools[4], label: "1" },
    { color: colorScales.numberOfSchools[6], label: "2" },
    { color: colorScales.numberOfSchools[8], label: "3" },
    { color: colorScales.numberOfSchools[10], label: "4+" },
  ],
};
